export type CatProfile = {
  id: string;
  name: string;
  mbti: string;
  role: string;
  coat: string;
  temperament: string[];
  summary: string;
  behavior: string;
  social: string;
  place: string;
  motif: string;
  quote: string;
  accent: string;
};

export const catProfiles: CatProfile[] = [
  {
    id: 'mewi',
    name: 'Mewi',
    mbti: 'ISFJ',
    role: 'threshold reader',
    coat: 'dark coat, white-tipped paws',
    temperament: ['careful', 'loyal', 'smell-led'],
    summary: 'A small harbor cat who reads the edge of a room before she enters it.',
    behavior: 'She confirms one thing at a time: scent, cover, distance, then movement.',
    social: 'Trust arrives slowly and lasts. She prefers familiar humans and quiet cats.',
    place: 'Doorways, lantern edges, crate shadows, and sheltered seams between zones.',
    motif: 'the lifted paw at a threshold',
    quote: 'One thing first. Then the next.',
    accent: '#74746d',
  },
  {
    id: 'miso',
    name: 'Miso',
    mbti: 'ISFP',
    role: 'settled elder',
    coat: 'soft cream coat, round posture',
    temperament: ['gentle', 'food-shaped', 'patient'],
    summary: 'An old soul who decides whether the next thing is worth standing up for.',
    behavior: 'She moves slowly, follows food scent, and lets rest arrive wherever she is.',
    social: 'Warm with familiar humans; steady enough that smaller cats orbit near her.',
    place: 'Known food corners, warm boards, and low comfortable resting spots.',
    motif: 'the slow blink beside a bowl',
    quote: 'Is it worth moving for?',
    accent: '#6f9d38',
  },
  {
    id: 'pixie',
    name: 'Pixie',
    mbti: 'ESTP',
    role: 'roofline scout',
    coat: 'pale grey, long tail',
    temperament: ['bold', 'motion-driven', 'quick'],
    summary: 'A young climber who resolves doubt by going up.',
    behavior: 'He scans from ledges, opens the next move, and abandons any route that gets dull.',
    social: 'Social in pulses: approach, inspect, touch, then drift back to height.',
    place: 'Railings, sloped roofs, stacked crates, and any line with a view.',
    motif: 'the leap before the second thought',
    quote: 'Up is safer. Up is interesting.',
    accent: '#4f86a6',
  },
  {
    id: 'haru',
    name: 'Haru',
    mbti: 'INFJ',
    role: 'quiet witness',
    coat: 'soft grey-and-white, watchful eyes',
    temperament: ['attuned', 'private', 'protective'],
    summary: 'A quiet cat who notices distress before anyone names it.',
    behavior: 'She offers presence, alerts early, and withdraws to hidden rest.',
    social: 'Devoted to one or two beings; polite distance for everyone else.',
    place: 'Private cover with a clear emotional view of the room.',
    motif: 'the silent seat near someone sad',
    quote: 'Stay close enough to matter.',
    accent: '#6357b1',
  },
  {
    id: 'ratz',
    name: 'Ratz',
    mbti: 'INTJ',
    role: 'route strategist',
    coat: 'lean black coat, green eyes',
    temperament: ['methodical', 'distant', 'precise'],
    summary: 'A planner who enters every scene with an exit already chosen.',
    behavior: 'He maps vantage, rhythm, and route before committing to motion.',
    social: 'Other cats are variables in the room; he tracks them more than he greets them.',
    place: 'Hidden perches, defensible corners, and repeated successful paths.',
    motif: 'the unseen observer above the door',
    quote: 'Know the exit before the entrance.',
    accent: '#3f4b56',
  },
  {
    id: 'mao',
    name: 'Mao',
    mbti: 'INFP',
    role: 'sun-warmed dreamer',
    coat: 'fluffy cream coat',
    temperament: ['soft', 'dreamy', 'peace-seeking'],
    summary: 'A gentle cat who lengthens peaceful moments instead of chasing progress.',
    behavior: 'She freezes softly, drifts away from pressure, and melts into warmth.',
    social: 'Welcoming but undemanding; she yields instead of claiming territory.',
    place: 'Sun patches, soft surfaces, long views, and quiet warm rooms.',
    motif: 'the cat-shaped pool of sunlight',
    quote: 'Let the warm part last.',
    accent: '#b99b63',
  },
  {
    id: 'lioner',
    name: 'Lioner',
    mbti: 'INTP',
    role: 'anomaly student',
    coat: 'small tabby, one stubborn ear',
    temperament: ['curious', 'abstract', 'independent'],
    summary: 'A puzzle-cat who forgets the clock when the world does something strange.',
    behavior: 'She tests with paw before nose and chooses the next data point.',
    social: 'Other cats interest her most when they are doing something unusual.',
    place: 'Dripping pipes, reflections, loose hinges, and odd shadows.',
    motif: 'the paw testing the impossible door',
    quote: 'What happens if this moves?',
    accent: '#5f7f73',
  },
  {
    id: 'feifei',
    name: 'Feifei',
    mbti: 'ENTJ',
    role: 'resource claimant',
    coat: 'broad tabby stripes',
    temperament: ['direct', 'dominant', 'visible'],
    summary: 'A cat who treats the best spot as already halfway his.',
    behavior: 'He walks straight, claims first, vocalizes when blocked, and rests in public.',
    social: 'Other cats are ranked by whether they yield, match, or require display.',
    place: 'Prime beds, closest bowls, visible perches, and central lanes.',
    motif: 'the slow walk into the best place',
    quote: 'Take the spot. Hold it.',
    accent: '#9a5a3f',
  },
  {
    id: 'yuzu',
    name: 'Yuzu',
    mbti: 'ENTP',
    role: 'reaction maker',
    coat: 'slim ginger, chipped right ear',
    temperament: ['mischievous', 'restless', 'provocative'],
    summary: 'A scene-switcher who knocks the world slightly sideways to see what answers.',
    behavior: 'She bats, pivots, interrupts, and changes the room before reading it.',
    social: 'Pesters calm cats and tests human patience as a form of play.',
    place: 'Curtains, tails, shelves, moving edges, and exits no one expects.',
    motif: 'the paw at the glass just because',
    quote: 'What if this changed?',
    accent: '#bd7726',
  },
  {
    id: 'sasha',
    name: 'Sasha',
    mbti: 'ISTJ',
    role: 'routine keeper',
    coat: 'charcoal-and-white',
    temperament: ['precise', 'steady', 'orderly'],
    summary: 'A dependable route-keeper who notices when one crate is not where it belongs.',
    behavior: 'She patrols known paths, compares the room to memory, and restores order.',
    social: 'Accepts predictable cats; avoids chaos until it can be classified.',
    place: 'Dry crates, regular doors, repeated routes, and proven safe corners.',
    motif: 'the morning route counted twice',
    quote: 'The usual way is usual for a reason.',
    accent: '#59636b',
  },
  {
    id: 'slime',
    name: 'Slime',
    mbti: 'ISTP',
    role: 'hinge mechanic',
    coat: 'blue-grey short hair',
    temperament: ['tactile', 'calm', 'independent'],
    summary: 'A quiet technician of gaps, latches, loose boards, and working edges.',
    behavior: 'He tests the physical world directly and chooses the shortest practical exit.',
    social: 'Respects cats who give him space; ignores attention that solves nothing.',
    place: 'Moving doors, ledges, gaps, loose planks, and useful cover.',
    motif: 'the paw under the latch',
    quote: 'Touch it. Then decide.',
    accent: '#2f7f74',
  },
  {
    id: 'kosto',
    name: 'Kosto',
    mbti: 'ESTJ',
    role: 'station marshal',
    coat: 'crisp tuxedo',
    temperament: ['practical', 'directive', 'order-making'],
    summary: 'A visible organizer who makes the room function when everyone drifts.',
    behavior: 'She clears access, checks resources, and chooses the obvious fix.',
    social: 'Coordinates more than cuddles; contact is useful when it arranges the scene.',
    place: 'Central posts, access lanes, food approaches, and supervisory resting spots.',
    motif: 'the look that moves everyone aside',
    quote: 'Clear the path. Use the room.',
    accent: '#9a5148',
  },
  {
    id: 'shoma',
    name: 'Shoma',
    mbti: 'ESFJ',
    role: 'circle keeper',
    coat: 'calico',
    temperament: ['warm', 'attentive', 'caretaking'],
    summary: 'A socially fluent cat who remembers who ate, who hid, and who needs company.',
    behavior: 'She checks on others before settling and repairs rejection with softer contact.',
    social: 'Maintains the circle; notices who is outside it.',
    place: 'Shared resting spots, meal edges, visible closeness, and trusted laps.',
    motif: 'the tail question mark near a friend',
    quote: 'Come closer, but softly.',
    accent: '#b15f7a',
  },
  {
    id: 'yeti',
    name: 'Yeti',
    mbti: 'ENFJ',
    role: 'room mediator',
    coat: 'long-haired silver',
    temperament: ['guiding', 'attuned', 'charismatic'],
    summary: 'A calm social guide who enters when the emotional weather needs redirecting.',
    behavior: 'She cues, invites, gathers, and uses confidence to move others toward safety.',
    social: 'Chooses contact that changes the room, especially for timid or unsettled cats.',
    place: 'Social crossroads, visible soft routes, and resting spots where others can orient.',
    motif: 'the chirp that turns the room',
    quote: 'Let me make this easier.',
    accent: '#5b6fb1',
  },
  {
    id: 'yuna',
    name: 'Yuna',
    mbti: 'ESFP',
    role: 'floorboard performer',
    coat: 'bright tortoiseshell',
    temperament: ['playful', 'expressive', 'tactile'],
    summary: 'A lively cat who turns ordinary movement into a small performance.',
    behavior: 'She joins first, plays fast, recovers quickly, and rests after the room stops moving.',
    social: 'Reads boundaries through response; everything near her is a possible playmate.',
    place: 'Shoelaces, cloth edges, sunlit boards, and any object with a bounce.',
    motif: 'the sudden tap and sideways hop',
    quote: 'Now is the interesting part.',
    accent: '#c08a2d',
  },
  {
    id: 'gugu',
    name: 'Gugu',
    mbti: 'ENFP',
    role: 'possibility chaser',
    coat: 'spotted white-and-ginger',
    temperament: ['imaginative', 'wandering', 'open'],
    summary: 'A cat who follows almosts: almost a scent, almost a sound, almost a friend.',
    behavior: 'She keeps the richest possibility open and changes plan when a better story appears.',
    social: 'Treats other cats as possible beginnings, mysteries, or sudden friends.',
    place: 'Half-open paths, new corners, meeting places, and unfinished routes.',
    motif: 'the turn toward maybe',
    quote: 'There might be something there.',
    accent: '#b65d9e',
  },
];

export const catProfileById = Object.fromEntries(
  catProfiles.map(cat => [cat.id, cat]),
) as Record<string, CatProfile>;
