name: mewi-report

services:
  report_viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mewi_report_viewer
    restart: unless-stopped
    ports:
      - "4321:4321"
    environment:
      ASTRO_TELEMETRY_DISABLED: "1"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./pipeline/processed_data:/app/src/data:ro
