name: Run Eval on Merge
on:
  push:
    branches: [main]

jobs:
  eval:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          # Where your S3 buckets live
          aws-region: ap-southeast-2

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      ## Unit test for basic 
      - name: Run local make test

      ## If need edit agents/ got revise then need to run evals
      - name: Download dataset from S3
        run: aws s3 cp s3://mewi-eval-dataset-v0/smoke.json ./backend/evals/backend/datasets/smoke.json

      - name: Run backend eval
        run: uv run python backend/evals/run_eval.py --eval_type backend

      - name: Upload results to S3
        run: aws s3 cp ./backend/evals/backend/results/ s3://mewi-eval-result-v0/runs/${{ github.sha }}/ --recursive